FROM python:3.6
ENV PYTHONUNBUFFERED 1

# Get scion dependency
RUN git clone https://github.com/netsec-ethz/netsec-scion.git -b scionlab --depth 1 /tmp/scion

RUN pip install --upgrade pip
COPY requirements.txt dev-requirements.txt /scionlab/
WORKDIR /scionlab/
RUN pip install -r requirements.txt -r dev-requirements.txt

COPY . /scionlab/

# Fixup django settings for the integration tests:
RUN sed -i 's/^SCIONLAB_SITE = .*/SCIONLAB_SITE = "http:\/\/coord:8000"/' scionlab/settings/development.py

# Install SSH config for host deployment
RUN mkdir ~/.ssh && cp .circleci/setup/deploy_ssh_config ~/.ssh/ssh_config; cp .circleci/setup/deploy_rsa* ~/.ssh/

# Load fixtures and initalize test DB
ENV PYTHONPATH /tmp/scion/python

CMD ["manage.py","runserver","0.0.0.0:8000"]
