FROM ubuntu:xenial

# Install base
RUN apt-get update && apt-get install --assume-yes \
  systemd \
  libpcap0.8 libpcap0.8-dev \ 
  apt-transport-https \
  openssh-server inotify-tools

# systemd
ENV container docker
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i = systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*; \
rm -f /etc/systemd/system/*.wants/*; \
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*; \
rm -f /lib/systemd/system/anaconda.target.wants/*;
VOLUME [ "/sys/fs/cgroup" ]

# Install SCION
RUN bash -c 'echo "deb [trusted=yes] https://packages.netsec.inf.ethz.ch/debian all main" >> /etc/apt/sources.list'
RUN apt-get update && apt-get install --assume-yes scionlab

# Overwrite scionlab-config script with version from repo
COPY scionlab/hostfiles/scionlab-config /usr/bin/


CMD ["/usr/bin/systemd"]
