FROM python:3.6
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
COPY requirements.txt dev-requirements.txt /scionlab/
WORKDIR /scionlab/
RUN pip install -r requirements.txt -r dev-requirements.txt

COPY . /scionlab/

# Fixup django settings for the integration tests:
RUN sed -i 's/^SCIONLAB_SITE = .*/SCIONLAB_SITE = "http:\/\/coord:8000"/' scionlab/settings/development.py

# Add /scionlab/ to PYTHONPATH to simplify running the scripts in .circleci/actions/
ENV PYTHONPATH /scionlab/

CMD ["python", "manage.py","runserver","0.0.0.0:8000"]
