services:
  db:
    # Latest postgres docker image uses the new Debian bookworm and it is incompatible with some
    # existing docker implementations. CircleCI runs one of those older implementations.
    # Pinning the image to N-bullseye (prior Debian distribution) as a workaround.
    # https://github.com/docker-library/postgres/issues/1100
    # image: postgres:latest
    image: postgres:12-bullseye
    expose:
      - "5432"
    environment:
      POSTGRES_DB: scionlab_coordinator
      POSTGRES_USER: scionlab_rw
      POSTGRES_PASSWORD: scionlab_rw_passw0rd
