#!/bin/bash

# get script location, thanks: https://stackoverflow.com/a/246128/28578
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     ${DIR}/scion-pki-linux "$@" ;;
    Darwin*)    ${DIR}/scion-pki-mac "$@" ;;
    CYGWIN*)    echo "Cygwin not supported" && exit 1;;
    MINGW*)     echo "Mingw not supported" && exit 1;;
    *)          echo "Unknown machine: ${unameOut}" && exit 1
esac
