# Collect static files in /scionlab/static
FROM python:3 AS static_builder
ENV PYTHONUNBUFFERED 1

# Clone SCION repo to get it's python modules
RUN git clone https://github.com/netsec-ethz/netsec-scion/ /scion
ENV PYTHONPATH=/scion/python:/scion

RUN mkdir /scionlab
WORKDIR /scionlab
COPY requirements.txt /scionlab/
RUN pip install -r requirements.txt
COPY . /scionlab/

ENV DJANGO_SETTINGS_MODULE=scionlab.settings.production
RUN /scionlab/manage.py collectstatic

# Build the caddy image
# TODO all these caddy base images seem rather crappy
FROM yobasystems/alpine-caddy

COPY --from=static_builder /scionlab/static /var/www/scionlab/static
COPY deploy/Caddyfile /etc/
