version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: scionlab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    expose:
      - "5432"
  # redis
  # huey
  django:
    build: .
    environment:
      POSTGRES_DB: scionlab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    expose:
      - "8000"
    depends_on:
      - db

  proxy:
    build:
      context: .
      dockerfile: Dockerfile-caddy
    depends_on:
      - django
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.caddy:/root/.caddy
