# Generated by Django 2.2 on 2019-05-23 07:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.encoder
import jsonfield.fields
import re
import scionlab.models.user


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('password', models.CharField(max_length=255, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('organisation', models.CharField(blank=True, max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', scionlab.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('as_id', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(regex=re.compile('^([0-9a-fA-F]{1,4}):([0-9a-fA-F]{1,4}):([0-9a-fA-F]{1,4})$')), django.core.validators.RegexValidator(inverse_match=True, regex='0+:0+:0+')], verbose_name='AS-ID')),
                ('as_id_int', models.BigIntegerField(editable=False)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('mtu', models.PositiveIntegerField(default=1472, help_text='Maximum Transfer Unit for intra AS packets.')),
                ('sig_pub_key', models.CharField(blank=True, max_length=255, null=True)),
                ('sig_priv_key', models.CharField(blank=True, max_length=255, null=True)),
                ('enc_pub_key', models.CharField(blank=True, max_length=255, null=True)),
                ('enc_priv_key', models.CharField(blank=True, max_length=255, null=True)),
                ('master_as_key', models.CharField(blank=True, max_length=255, null=True)),
                ('is_core', models.BooleanField(default=False)),
                ('core_sig_priv_key', models.CharField(blank=True, max_length=255, null=True)),
                ('core_sig_pub_key', models.CharField(blank=True, max_length=255, null=True)),
                ('core_online_priv_key', models.CharField(blank=True, max_length=255, null=True)),
                ('core_online_pub_key', models.CharField(blank=True, max_length=255, null=True)),
                ('core_offline_priv_key', models.CharField(blank=True, max_length=255, null=True)),
                ('core_offline_pub_key', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate_chain', jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}, null=True)),
                ('core_certificate', jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}, null=True)),
            ],
            options={
                'verbose_name': 'AS',
                'verbose_name_plural': 'ASes',
            },
        ),
        migrations.CreateModel(
            name='BorderRouter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_port', models.PositiveIntegerField(blank=True)),
                ('control_port', models.PositiveIntegerField(blank=True)),
                ('AS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='border_routers', to='scionlab.AS')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_ip', models.GenericIPAddressField(default='127.0.0.1', help_text='IP of the host in the AS')),
                ('public_ip', models.GenericIPAddressField(blank=True, help_text='Default public IP for for border router interfaces running on this host.', null=True)),
                ('bind_ip', models.GenericIPAddressField(blank=True, help_text='Default bind IP for for border router interfaces running on this host.', null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('managed', models.BooleanField(default=False)),
                ('ssh_host', models.CharField(blank=True, help_text='Hostname or IP for management access via SSH. Configured in run/ssh_config.', max_length=255, null=True)),
                ('uid', models.CharField(editable=False, help_text='Identifier for API', max_length=255, unique=True, verbose_name='UID')),
                ('secret', models.CharField(help_text='Secret token for API', max_length=255)),
                ('config_version', models.PositiveIntegerField(default=1)),
                ('config_version_deployed', models.PositiveIntegerField(default=0)),
                ('AS', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosts', to='scionlab.AS')),
            ],
            options={
                'unique_together': {('AS', 'internal_ip')},
            },
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_id', models.PositiveSmallIntegerField()),
                ('public_ip', models.GenericIPAddressField(blank=True, help_text="Public IP for this interface. If this is not null, overrides the Host's default\n            public IP.", null=True)),
                ('public_port', models.PositiveIntegerField()),
                ('bind_ip', models.GenericIPAddressField(blank=True, help_text="Bind IP for this interface (optional). If `public_ip` (!) is not null, this\n            overrides the Host's default bind IP.", null=True)),
                ('bind_port', models.PositiveIntegerField(blank=True, null=True)),
                ('AS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='scionlab.AS')),
                ('border_router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='scionlab.BorderRouter')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='scionlab.Host')),
            ],
        ),
        migrations.CreateModel(
            name='ISD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('isd_id', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('trc', jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}, null=True, verbose_name='Trust Root Configuration (TRC)')),
                ('trc_priv_keys', jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, help_text='The private keys corresponding to the Core-AS keys in\n            the current TRC. These keys will be used to sign the next version\n            of the TRC.', load_kwargs={}, null=True, verbose_name='TRC private keys')),
            ],
            options={
                'verbose_name': 'ISD',
                'verbose_name_plural': 'ISDs',
            },
        ),
        migrations.CreateModel(
            name='VPN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_port', models.PositiveIntegerField()),
                ('subnet', models.CharField(max_length=15)),
                ('server_vpn_ip', models.GenericIPAddressField()),
                ('private_key', models.TextField(blank=True, null=True)),
                ('cert', models.TextField(blank=True, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpn_servers', to='scionlab.Host')),
            ],
            options={
                'verbose_name': 'VPN',
                'verbose_name_plural': 'VPNs',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.PositiveIntegerField(blank=True)),
                ('type', models.CharField(choices=[('BS', 'Beacon Server'), ('PS', 'Path Server'), ('CS', 'Certificate Server'), ('ZK', 'Zookeeper'), ('BW', 'Bandwidth tester server'), ('PP', 'Pingpong server')], max_length=16)),
                ('AS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='scionlab.AS')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='scionlab.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PROVIDER', 'Provider link from parent A to child B'), ('CORE', 'Core link (symmetric)'), ('PEER', 'Peering link (symmetric)')], max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('bandwidth', models.PositiveIntegerField(default=1000)),
                ('mtu', models.PositiveIntegerField(default=1472)),
                ('interfaceA', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link_as_interfaceA', to='scionlab.Interface')),
                ('interfaceB', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link_as_interfaceB', to='scionlab.Interface')),
            ],
        ),
        migrations.AddField(
            model_name='borderrouter',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='border_routers', to='scionlab.Host'),
        ),
        migrations.CreateModel(
            name='AttachmentPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AS', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_point_info', to='scionlab.AS')),
                ('vpn', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scionlab.VPN')),
            ],
        ),
        migrations.AddField(
            model_name='as',
            name='isd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ases', to='scionlab.ISD', verbose_name='ISD'),
        ),
        migrations.AddField(
            model_name='as',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VPNClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('active', models.BooleanField(default=True)),
                ('private_key', models.TextField(blank=True, null=True)),
                ('cert', models.TextField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpn_clients', to='scionlab.Host')),
                ('vpn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='scionlab.VPN')),
            ],
            options={
                'unique_together': {('vpn', 'ip')},
                'verbose_name': 'VPN Client',
                'verbose_name_plural': 'VPN Clients',
            },
        ),
        migrations.CreateModel(
            name='UserAS',
            fields=[
                ('as_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scionlab.AS')),
                ('public_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('bind_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('bind_port', models.PositiveIntegerField(blank=True, null=True)),
                ('installation_type', models.CharField(choices=[('VM', 'Install inside a virtual machine'), ('DEDICATED', 'Install on a dedicated system (for experts)')], default='VM', max_length=16)),
                ('attachment_point', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ases', to='scionlab.AttachmentPoint')),
            ],
            options={
                'verbose_name': 'User AS',
                'verbose_name_plural': 'User ASes',
            },
            bases=('scionlab.as',),
        ),
        migrations.AlterUniqueTogether(
            name='as',
            unique_together={('as_id',)},
        ),
    ]
