# Generated by Django 2.2 on 2019-08-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scionlab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='port',
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('BS', 'Beacon Server'), ('PS', 'Path Server'), ('CS', 'Certificate Server'), ('BW', 'Bandwidth tester server'), ('PP', 'Pingpong server')], max_length=16),
        ),
    ]
