# Generated by Django 3.1.6 on 2021-10-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scionlab', '0001_squashed_0011_pullap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('CS', 'Control Service'), ('SIG', 'SCION IP Gateway'), ('CO', 'Colibri Service'), ('BW', 'Bandwidth tester server'), ('PP', 'Pingpong server')], max_length=16),
        ),
    ]
