# Generated by Django 3.2 on 2021-09-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scionlab', '0001_squashed_0011_pullap'),
    ]

    operations = [
        migrations.AddField(
            model_name='borderrouter',
            name='is_hsr',
            field=models.BooleanField(default=False, help_text='If true, this is a high-speed router instance with special configuration.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('CS', 'Control Service'), ('SIG', 'SCION IP Gateway'), ('BW', 'Bandwidth tester server'), ('PP', 'Pingpong server')], max_length=16),
        ),
    ]
