# Generated by Django 2.2.4 on 2019-10-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scionlab', '0002_SCIONLab_upgrade-2019-08'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useras',
            name='attachment_point',
        ),
        migrations.RemoveField(
            model_name='useras',
            name='bind_ip',
        ),
        migrations.RemoveField(
            model_name='useras',
            name='bind_port',
        ),
        migrations.RemoveField(
            model_name='useras',
            name='public_ip',
        ),
        migrations.AddField(
            model_name='interface',
            name='is_over_vpn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='host',
            name='bind_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Default bind IP for border router interfaces running on this host.', null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='public_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Default public IP for border router interfaces running on this host.', null=True),
        ),
    ]
