# Generated by Django 2.2.4 on 2019-10-15 09:54

from django.db import migrations, models


def installation_type_dedicated_to_pkg(apps, schema_editor):
    UserAS = apps.get_model('scionlab', 'UserAS')
    UserAS.objects.filter(installation_type='DEDICATED').update(installation_type='PKG')


class Migration(migrations.Migration):

    dependencies = [
        ('scionlab', '0002_SCIONLab_upgrade-2019-08'),
    ]

    operations = [
        migrations.RunPython(installation_type_dedicated_to_pkg),
        migrations.AlterField(
            model_name='useras',
            name='installation_type',
            field=models.CharField(choices=[('VM', 'Run SCION in a <em>Vagrant</em> virtual machine <i class="text-muted">(simplest approach)</i>'), ('PKG', 'SCION installation from packages'), ('SRC', 'SCION installation from sources <i class="text-muted">(for developers)</i>')], default='VM', max_length=16),
        ),
    ]
