# Generated by Django 2.2.4 on 2019-09-23 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scionlab', '0002_SCIONLab_upgrade-2019-08'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useras',
            name='attachment_point',
        ),
        migrations.RemoveField(
            model_name='useras',
            name='bind_ip',
        ),
        migrations.RemoveField(
            model_name='useras',
            name='bind_port',
        ),
        migrations.RemoveField(
            model_name='useras',
            name='public_ip',
        ),
        migrations.AddField(
            model_name='interface',
            name='vpn_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scionlab.VPNClient'),
        ),
        migrations.AlterField(
            model_name='host',
            name='bind_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Default bind IP for border router interfaces running on this host.', null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='public_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Default public IP for border router interfaces running on this host.', null=True),
        ),
    ]
