# Generated by Django 2.2 on 2019-08-26 09:40

from django.db import migrations


def remove_zk(apps, schema_editor):
    Service = apps.get_model('scionlab', 'Service')
    Service.objects.filter(type='ZK').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('scionlab', '0002_remove_service_port'),
    ]

    operations = [
        migrations.RunPython(remove_zk)
    ]
