# Generated by Django 2.2.8 on 2020-02-10 07:46

from django.db import migrations, models


def combine_services_to_monolith(apps, schema_editor):
    """
    Convert Path Service (PS), Beacon Service (BS) and Certificate Service (CS) to the new
    monolithitical Control Service.
    For each AS, we need exactly one instance of this new service; we combine the service instances
    by dropping BS and PS, keeping only the CS instances. As we use are using the CS type identifier
    for the (old) Certificate Service and the (new) monolithical we don't even need to update the
    remaining entries.
    """
    Service = apps.get_model('scionlab', 'Service')
    Service.objects.filter(type__in=['PS', 'BS']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('scionlab', '0003_installation_types'),
    ]

    operations = [
        migrations.RunPython(combine_services_to_monolith),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('CS', 'Control Service'), ('BW', 'Bandwidth tester server'), ('PP', 'Pingpong server')], max_length=16),
        ),
    ]
