# Generated by Django 2.2.4 on 2019-11-20 07:58

from django.db import migrations, models


def move_ips_to_interface(apps, schema_editor):
    """
    Previously, we had stored public_ip and bind_ip on the level of the UserAS.host. With multiple
    attachment links per UserAS, we know store this information (only) in the (already existing)
    per-interface fields.
    """
    UserAS = apps.get_model('scionlab', 'UserAS')

    for useras in UserAS.objects.iterator():
        # UserASes have a unique host and before the multi-AP feature had a unique interface
        host = useras.hosts.get()
        iface = useras.interfaces.get()
        if not iface.public_ip:
            iface.public_ip = host.public_ip
            iface.bind_ip = host.bind_ip
            iface.save()
        host.public_ip = None
        host.bind_ip = None
        host.save()


class Migration(migrations.Migration):

    dependencies = [
        ('scionlab', '0003_installation_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useras',
            name='attachment_point',
        ),
        migrations.RemoveField(
            model_name='useras',
            name='bind_ip',
        ),
        migrations.RemoveField(
            model_name='useras',
            name='bind_port',
        ),
        migrations.RemoveField(
            model_name='useras',
            name='public_ip',
        ),
        migrations.AlterField(
            model_name='host',
            name='bind_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Default bind IP for border router interfaces running on this host.', null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='public_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Default public IP for border router interfaces running on this host.', null=True),
        ),

        # This does not depend on (similarly named) removed fields! Can be run before or after
        # removing fields
        migrations.RunPython(move_ips_to_interface),
    ]
