# Generated by Django 3.2 on 2021-11-25 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scionlab', '0003_colibri_service_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='bandwidth',
        ),
    ]
