# Generated by Django 2.2.8 on 2020-03-03 04:39

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scionlab', '0005_monolith'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.CharField(choices=[('as-decrypt', 'as-decrypt'), ('as-signing', 'as-signing'), ('as-cert-signing', 'as-cert-signing'), ('trc-issuing-grant', 'trc-issuing-grant'), ('trc-voting-online', 'trc-voting-online'), ('trc-voting-offline', 'trc-voting-offline')], editable=False, max_length=16)),
                ('version', models.PositiveIntegerField(editable=False)),
                ('not_before', models.DateTimeField()),
                ('not_after', models.DateTimeField()),
                ('key', models.CharField(editable=False, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='as',
            name='certificate_chain',
        ),
        migrations.RemoveField(
            model_name='as',
            name='core_certificate',
        ),
        migrations.RemoveField(
            model_name='as',
            name='core_offline_priv_key',
        ),
        migrations.RemoveField(
            model_name='as',
            name='core_offline_pub_key',
        ),
        migrations.RemoveField(
            model_name='as',
            name='core_online_priv_key',
        ),
        migrations.RemoveField(
            model_name='as',
            name='core_online_pub_key',
        ),
        migrations.RemoveField(
            model_name='as',
            name='core_sig_priv_key',
        ),
        migrations.RemoveField(
            model_name='as',
            name='core_sig_pub_key',
        ),
        migrations.RemoveField(
            model_name='as',
            name='enc_priv_key',
        ),
        migrations.RemoveField(
            model_name='as',
            name='enc_pub_key',
        ),
        migrations.RemoveField(
            model_name='as',
            name='sig_priv_key',
        ),
        migrations.RemoveField(
            model_name='as',
            name='sig_pub_key',
        ),
        migrations.RemoveField(
            model_name='isd',
            name='trc',
        ),
        migrations.RemoveField(
            model_name='isd',
            name='trc_priv_keys',
        ),
        migrations.CreateModel(
            name='TRC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(editable=False)),
                ('not_before', models.DateTimeField()),
                ('not_after', models.DateTimeField()),
                ('trc', jsonfield.fields.JSONField(dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, editable=False, load_kwargs={})),
                ('isd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trcs', to='scionlab.ISD', verbose_name='ISD')),
                ('voting_offline', models.ManyToManyField(to='scionlab.Key')),
            ],
            options={
                'verbose_name': 'TRC',
                'verbose_name_plural': 'TRCs',
            },
        ),
        migrations.AddField(
            model_name='key',
            name='AS',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='scionlab.AS'),
        ),
        migrations.AlterUniqueTogether(
            name='key',
            unique_together={('AS', 'usage', 'version')},
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('issuer', 'issuer'), ('chain', 'chain')], editable=False, max_length=16)),
                ('version', models.PositiveIntegerField()),
                ('not_before', models.DateTimeField()),
                ('not_after', models.DateTimeField()),
                ('certificate', jsonfield.fields.JSONField(dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={})),
                ('AS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='scionlab.AS')),
            ],
            options={
                'unique_together': {('AS', 'type', 'version')},
            },
        ),
    ]
