# Generated by Django 3.0.7 on 2020-09-16 04:27

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scionlab', '0006_pki'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentpoint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='trc',
            name='trc',
            field=jsonfield.fields.JSONField(editable=False),
        ),
    ]
