# Generated by Django 3.0.7 on 2020-11-26 02:41

from django.db import migrations


def remove_as_pki(apps, schema_editor):
    # remove TRCs
    TRC = apps.get_model('scionlab', 'TRC')
    TRC.objects.all().delete()
    # remove certs
    Certificate = apps.get_model('scionlab', 'Certificate')
    Certificate.objects.all().delete()
    # remove keys
    Key = apps.get_model('scionlab', 'Key')
    Key.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('scionlab', '0006_pki'),
    ]

    operations = [
        migrations.RunPython(remove_as_pki),
    ]
