# Generated by Django 3.0.7 on 2020-11-05 12:42

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scionlab', '0006_pki'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='managed',
        ),
        migrations.AddField(
            model_name='host',
            name='config_queried_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='trc',
            name='trc',
            field=jsonfield.fields.JSONField(editable=False),
        ),
    ]
