# Generated by Django 3.2.5 on 2022-02-09 05:18

from django.db import migrations, models


def copy_ssh_host_to_label(apps, schema_editor):
    Host = apps.get_model("scionlab", "Host")
    Host.objects.filter(label=None).exclude(ssh_host=None).update(label=models.F('ssh_host'))


class Migration(migrations.Migration):

    dependencies = [
        ('scionlab', '0006_bump_version_cs_hosts'),
    ]

    operations = [
        migrations.RunPython(copy_ssh_host_to_label,  # forward
                             lambda a, b: None),      # backward
        migrations.RemoveField(
            model_name='host',
            name='ssh_host',
        ),
        migrations.AlterField(
            model_name='host',
            name='label',
            field=models.CharField(blank=True, help_text='Hostname. For managed hosts, this should correspond to the hostname used in the ansible inventory.', max_length=255, null=True),
        ),
    ]
