# Generated by Django 3.0.7 on 2020-12-10 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scionlab', '0008_new_cppki_cont'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interface',
            name='bind_port',
        ),
    ]
