# Generated by Django 3.2.20 on 2024-06-12 02:31

from django.db import migrations

from scionlab.models.core import Host


def bump_version(apps, schema_editor):
    """
    Data migration: bump the version of all hosts.
    """
    Host.objects.bump_config()

class Migration(migrations.Migration):

    dependencies = [
        ('scionlab', '0008_remove_colibri'),
    ]

    operations = [
        migrations.RunPython(bump_version,        # forward
                             lambda a, b: None),  # backward
    ]
