# Generated by Django 3.2.20 on 2024-09-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scionlab', '0009_allhosts_dirty'),
    ]

    operations = [
        migrations.AddField(
            model_name='as',
            name='fabrid_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
