# Generated by Django 3.0.7 on 2020-12-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scionlab', '0010_remove_router_internal_port_ctrl_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='managed',
        ),
        migrations.AddField(
            model_name='host',
            name='config_queried_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
